Feature user menu
LiamCusack/Crate pull request #56
Opened 2021-03-29 21:51 UTC by lbmerchant93

## *Purpose:*

- [x] Adds a new feature
- [x] Improves an existing feature
- [ ] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*

Creates the User Menu that is displayed at the top of the Profile and Orders components. Creates the Orders component with a simple message to display that the component and route that was created for it both work. 

## *What are the relevant tickets?*
 
Closes 52

## *Bugs:*

Orders component still needs all of the different elements that are to be displayed. Profile has the preview commented out code still in order to explain what what changed. 

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change
- [x] I used a rebase workflow

## *Notes:*
Need information on how the API response will look in order to display the correct Orders information, can put in some sample data if we want to.

2021-03-29 21:57 UTC, christina-cook commented
This menu looks good. Buttons are routing to the correct paths. Now we can style the Orders component and add the rest of the elements needed on the profile page.

2021-03-29 22:00 UTC, mainlyetcetera requested changes
No issues with the code itself. Just real picky stuff from me about spacing and punctuation.

2021-03-29 22:00 UTC, mainlyetcetera commented on code/web/src/modules/user/common/Menu.js
> +  }
Super, super picky from me. This `}` is still 2 spaces out from the edge. Looks like these docs have a mix of 2-space indents and 4. We will want to match where we see it, I think.

2021-03-29 22:00 UTC, mainlyetcetera commented on code/web/src/modules/user/Orders.js
> +export default Orders;
I advocate for removing the `;` here. Looks like, throughout the codebase, the original authors opted not to use them.

2021-03-29 22:09 UTC, christina-cook approved these changes
Code looks good and menu buttons are routing to the correct paths. Now we can add the rest of the elements needed on the profile page.

2021-03-30 02:23 UTC, mainlyetcetera commented on code/web/src/modules/user/common/Menu.js
> +  }
This looks much better. Thanks for addressing this!

2021-03-30 02:23 UTC, mainlyetcetera approved these changes

2021-03-30 02:24 UTC, merged